version: 0.0
os: linux 
files:
  - source: /*
    destination: /app/
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/afterInstall
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/startServer
      timeout: 300
      runas: root