#!/bin/bash
yum update -y
yum install ruby -y
yum install wget -y
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
export NVM_DIR="/.nvm"
[ -s "/.nvm/nvm.sh" ] && \. "/.nvm/nvm.sh"
nvm install node
nvm use node
node -v
npm install npm@latest -g
npm -v
cd /home/ec2-user
wget https://aws-codedeploy-us-west-2.s3.amazonaws.com/latest/install
chmod +x ./install
./install auto
service codedeploy-agent status
--//